{% set version = "1.4.15" %}
{% set sha256 = "205ebe8301ac8e259ade14c755043049c39dbdb3daab71ee71ae9cc2f0b9fc7e" %}

package:
  name: menuinst
  version: {{ version }}

source:
  fn: menuinst-{{ version }}.tar.gz
  url: https://github.com/ContinuumIO/menuinst/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not win]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
    - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"
  entry_points:
    - menuinst = menuinst.main:main
  skip_compile_pyc:
    - cwp.py

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pywin32

test:
  imports:
    - menuinst

  commands:
    - menuinst --help

about:
  home: https://github.com/ContinuumIO/menuinst
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "cross platform install of menu items"

  dev_url: https://github.com/ContinuumIO/menuinst
  doc_url: https://github.com/ContinuumIO/menuinst/wiki

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
