{% set version = "1.4.14" %}
{% set sha256 = "c52582f1bbcbb27976cc8c7c50baac41a50747d599178e8e3b8bca10edd0c7e2" %}

package:
  name: menuinst
  version: {{ version }}

source:
  fn: menuinst-{{ version }}.tar.gz
  url: https://github.com/ContinuumIO/menuinst/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [not win]
  script:
    - python -m pip install --no-deps --ignore-installed .
    - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"
  entry_points:
    - menuinst = menuinst.main:main
  skip_compile_pyc:
    - cwp.py

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pywin32

test:
  imports:
    - menuinst

  commands:
    - menuinst --help

about:
  home: https://github.com/ContinuumIO/menuinst
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "cross platform install of menu items"

  dev_url: https://github.com/ContinuumIO/menuinst
  doc_url: https://github.com/ContinuumIO/menuinst/wiki

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
