{% set version = "1.4.19" %}
{% set sha256 = "f93ef4bc4e627868b7bba62ef8cb675e84d5bbe69a85a03a7559e1979f3924ec" %}

package:
  name: menuinst
  version: {{ version }}

source:
  fn: menuinst-{{ version }}.tar.gz
  url: https://github.com/conda/menuinst/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-switch-admin-nonadmin-file.patch

build:
  number: 2
  skip: True  # [not win]
  script:
    - {{ PYTHON }} -m pip install . -vv
    - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"
  entry_points:
    - menuinst = menuinst.main:main
  skip_compile_pyc:
    - cwp.py

requirements:
  build:
    - {{ compiler('cxx') }}
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - menuinst
  requires:
    - pip
  commands:
    - pip check
    - menuinst --help

about:
  home: https://github.com/conda/menuinst
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: cross platform install of menu items
  description: |
    This application is used by Conda to create shortcuts on a wide variety of
    systems.
  dev_url: https://github.com/conda/menuinst
  doc_url: https://github.com/conda/menuinst/wiki

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
