{% set version = "1.4.17" %}
{% set sha256 = "143bc78efbbe9e34698df3d40f20576ccd9b62a199ebfff83cc5515049f70090" %}

package:
  name: menuinst
  version: {{ version }}

source:
  fn: menuinst-{{ version }}.tar.gz
  url: https://github.com/conda/menuinst/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not win]
  script:
    - {{ PYTHON }} -m pip install . -vv
    - copy "%SRC_DIR%\\cwp.py" "%PREFIX%\\"
  entry_points:
    - menuinst = menuinst.main:main
  skip_compile_pyc:
    - cwp.py

requirements:
  build:
    - {{ compiler('cxx') }}
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pywin32

test:
  imports:
    - menuinst
  requires:
    - pip
  commands:
    - pip check
    - menuinst --help

about:
  home: https://github.com/ContinuumIO/menuinst
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: cross platform install of menu items
  description: |
    This application is used by Conda to create shortcuts on a wide variety of
    systems.
  dev_url: https://github.com/conda/menuinst
  doc_url: https://github.com/conda/menuinst/wiki

extra:
  recipe-maintainers:
    - goanpeca
    - jakirkham
    - carlodri
