travis:
  secure:
    BINSTAR_TOKEN: Dt90CCvh999fR+0nDuoAdgsoqICbcOn1EXHE57w5fao6kdDnY15OodU9JVubDbPxcOynL6VvZuEE/HY9691GCKBFhvj7R5IwRxZNuFuK/qgfpigTTy7ZN8exuckTZ7P5ju3GMFSEKO5YW/Z8nX8+5yJwuaggYahZ2EDtu7TMpobBPv8NYdDzECE4ievAD0RZRzq6mJYWQ6hbBsUrubOvtSNygsBuysGQP/FZ7hxcJTVlzqdPLbJfmrn5oagWaQMQAXjFQoNXK6yK5TPbiJKSwsOkj9bzYjY5dugFjcB/0vCikOGeF7YbH7ovxO0+UzmXzIuDu2ZQMDbrP5W1owZyVEzzPrEhFQfUfoIRQcgNZgbK6I/M6cas/hC7VtaHQ2msx51hwzrwlzQ3oceT46rchnvJCgEGtSpiFYcDTSZvGbKbsO3LuwXt28NcL+JxlR7lO1gk41rbD4+5l5nSohoaLvHkQwsLn/I3x8rme931WiKcSUdSrvRirmNJoEGlXzMzZzLJBADVb8kD2friHAuGtCbqwUUhKO+rUsoLZ9pfggQV6fZQUuofMohsusMj/UhU/zA8KG/70FX7Jpcpp5FJz+O9cK0P4ggioAn4o1GKn7IYWxSDvW+BoHxb8rfnUhiGsT3Cbv3ogVAa4Tn+SnGgNugRdzzHhi7RD12aa7GfhQI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
